export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/product'
export const ADMIN_ROUTE = '/admin'
export const SHIPPING_ROUTE = '/shipping'
export const ADMIN_DASHBOARD_ROUTE = '/admin/dashboard'